# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js image as a base
FROM node:20-alpine AS builder

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json tsconfig.json ./

# Install project dependencies
RUN --mount=type=cache,target=/root/.npm npm install

# Copy the rest of the application's source code
COPY src/ ./src/

# Build the TypeScript project
RUN npm run build

# Use a lightweight Node.js image for the production build
FROM node:20-alpine

RUN apk add --no-cache python3 py3-pip build-base uv

# Link python3 to python for convenience
RUN ln -sf python3 /usr/bin/python


RUN uv tool install mcp-proxy

# Set the working directory in the container
WORKDIR /app

# Copy the built files and node_modules from the builder stage
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules

COPY named-server-config.json ./.

EXPOSE 32009

# Start the server
CMD ["uvx", "mcp-proxy", "--port=32009", "--host=0.0.0.0", "--named-server-config", "./named-server-config.json"]
